/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BookCampaignRouteImport } from './routes/book-campaign'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CreatorsRouteImport } from './routes/creators'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBlogsRouteImport } from './routes/admin.blogs'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminBlogsIndexRouteImport } from './routes/admin.blogs.index'
import { Route as AdminBlogsNewRouteImport } from './routes/admin.blogs.new'
import { Route as AdminTestimonialsIndexRouteImport } from './routes/admin.testimonials.index'
import { Route as AdminTestimonialsNewRouteImport } from './routes/admin.testimonials.new'
import { Route as AdminBlogsIdEditRouteImport } from './routes/admin.blogs.$id.edit'
import { Route as AdminTestimonialsIdEditRouteImport } from './routes/admin.testimonials.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BookCampaignRoute = BookCampaignRouteImport.update({
  id: '/book-campaign',
  path: '/book-campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsRoute = CreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminBlogsIndexRoute = AdminBlogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminBlogsRoute,
} as any)
const AdminBlogsNewRoute = AdminBlogsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminBlogsRoute,
} as any)
const AdminTestimonialsIndexRoute = AdminTestimonialsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTestimonialsRoute,
} as any)
const AdminTestimonialsNewRoute = AdminTestimonialsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminTestimonialsRoute,
} as any)
const AdminBlogsIdEditRoute = AdminBlogsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminBlogsRoute,
} as any)
const AdminTestimonialsIdEditRoute = AdminTestimonialsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminTestimonialsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/blog': typeof BlogRouteWithChildren
  '/book-campaign': typeof BookCampaignRoute
  '/brands': typeof BrandsRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/creators': typeof CreatorsRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/blogs': typeof AdminBlogsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/testimonials': typeof AdminTestimonialsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/admin/testimonials/new': typeof AdminTestimonialsNewRoute
  '/admin/blogs/': typeof AdminBlogsIndexRoute
  '/admin/testimonials/': typeof AdminTestimonialsIndexRoute
  '/admin/blogs/$id/edit': typeof AdminBlogsIdEditRoute
  '/admin/testimonials/$id/edit': typeof AdminTestimonialsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/book-campaign': typeof BookCampaignRoute
  '/brands': typeof BrandsRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/creators': typeof CreatorsRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/admin/testimonials/new': typeof AdminTestimonialsNewRoute
  '/admin/blogs': typeof AdminBlogsIndexRoute
  '/admin/testimonials': typeof AdminTestimonialsIndexRoute
  '/admin/blogs/$id/edit': typeof AdminBlogsIdEditRoute
  '/admin/testimonials/$id/edit': typeof AdminTestimonialsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/blog': typeof BlogRouteWithChildren
  '/book-campaign': typeof BookCampaignRoute
  '/brands': typeof BrandsRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/creators': typeof CreatorsRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/blogs': typeof AdminBlogsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/testimonials': typeof AdminTestimonialsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/admin/testimonials/new': typeof AdminTestimonialsNewRoute
  '/admin/blogs/': typeof AdminBlogsIndexRoute
  '/admin/testimonials/': typeof AdminTestimonialsIndexRoute
  '/admin/blogs/$id/edit': typeof AdminBlogsIdEditRoute
  '/admin/testimonials/$id/edit': typeof AdminTestimonialsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/about'
    | '/admin'
    | '/apply'
    | '/blog'
    | '/book-campaign'
    | '/brands'
    | '/case-studies'
    | '/contact'
    | '/creators'
    | '/portfolio'
    | '/services'
    | '/sitemap.xml'
    | '/testimonials'
    | '/admin/blogs'
    | '/admin/login'
    | '/admin/testimonials'
    | '/blog/$slug'
    | '/admin/'
    | '/blog/'
    | '/admin/blogs/new'
    | '/admin/testimonials/new'
    | '/admin/blogs/'
    | '/admin/testimonials/'
    | '/admin/blogs/$id/edit'
    | '/admin/testimonials/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/about'
    | '/apply'
    | '/book-campaign'
    | '/brands'
    | '/case-studies'
    | '/contact'
    | '/creators'
    | '/portfolio'
    | '/services'
    | '/sitemap.xml'
    | '/testimonials'
    | '/admin/login'
    | '/blog/$slug'
    | '/admin'
    | '/blog'
    | '/admin/blogs/new'
    | '/admin/testimonials/new'
    | '/admin/blogs'
    | '/admin/testimonials'
    | '/admin/blogs/$id/edit'
    | '/admin/testimonials/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/about'
    | '/admin'
    | '/apply'
    | '/blog'
    | '/book-campaign'
    | '/brands'
    | '/case-studies'
    | '/contact'
    | '/creators'
    | '/portfolio'
    | '/services'
    | '/sitemap.xml'
    | '/testimonials'
    | '/admin/blogs'
    | '/admin/login'
    | '/admin/testimonials'
    | '/blog/$slug'
    | '/admin/'
    | '/blog/'
    | '/admin/blogs/new'
    | '/admin/testimonials/new'
    | '/admin/blogs/'
    | '/admin/testimonials/'
    | '/admin/blogs/$id/edit'
    | '/admin/testimonials/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApplyRoute: typeof ApplyRoute
  BlogRoute: typeof BlogRouteWithChildren
  BookCampaignRoute: typeof BookCampaignRoute
  BrandsRoute: typeof BrandsRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  CreatorsRoute: typeof CreatorsRoute
  PortfolioRoute: typeof PortfolioRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestimonialsRoute: typeof TestimonialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-campaign': {
      id: '/book-campaign'
      path: '/book-campaign'
      fullPath: '/book-campaign'
      preLoaderRoute: typeof BookCampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators': {
      id: '/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof CreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs': {
      id: '/admin/blogs'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/blogs/': {
      id: '/admin/blogs/'
      path: '/'
      fullPath: '/admin/blogs/'
      preLoaderRoute: typeof AdminBlogsIndexRouteImport
      parentRoute: typeof AdminBlogsRoute
    }
    '/admin/blogs/new': {
      id: '/admin/blogs/new'
      path: '/new'
      fullPath: '/admin/blogs/new'
      preLoaderRoute: typeof AdminBlogsNewRouteImport
      parentRoute: typeof AdminBlogsRoute
    }
    '/admin/testimonials/': {
      id: '/admin/testimonials/'
      path: '/'
      fullPath: '/admin/testimonials/'
      preLoaderRoute: typeof AdminTestimonialsIndexRouteImport
      parentRoute: typeof AdminTestimonialsRoute
    }
    '/admin/testimonials/new': {
      id: '/admin/testimonials/new'
      path: '/new'
      fullPath: '/admin/testimonials/new'
      preLoaderRoute: typeof AdminTestimonialsNewRouteImport
      parentRoute: typeof AdminTestimonialsRoute
    }
    '/admin/blogs/$id/edit': {
      id: '/admin/blogs/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/blogs/$id/edit'
      preLoaderRoute: typeof AdminBlogsIdEditRouteImport
      parentRoute: typeof AdminBlogsRoute
    }
    '/admin/testimonials/$id/edit': {
      id: '/admin/testimonials/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/testimonials/$id/edit'
      preLoaderRoute: typeof AdminTestimonialsIdEditRouteImport
      parentRoute: typeof AdminTestimonialsRoute
    }
  }
}

interface AdminBlogsRouteChildren {
  AdminBlogsNewRoute: typeof AdminBlogsNewRoute
  AdminBlogsIndexRoute: typeof AdminBlogsIndexRoute
  AdminBlogsIdEditRoute: typeof AdminBlogsIdEditRoute
}

const AdminBlogsRouteChildren: AdminBlogsRouteChildren = {
  AdminBlogsNewRoute: AdminBlogsNewRoute,
  AdminBlogsIndexRoute: AdminBlogsIndexRoute,
  AdminBlogsIdEditRoute: AdminBlogsIdEditRoute,
}

const AdminBlogsRouteWithChildren = AdminBlogsRoute._addFileChildren(
  AdminBlogsRouteChildren,
)

interface AdminTestimonialsRouteChildren {
  AdminTestimonialsNewRoute: typeof AdminTestimonialsNewRoute
  AdminTestimonialsIndexRoute: typeof AdminTestimonialsIndexRoute
  AdminTestimonialsIdEditRoute: typeof AdminTestimonialsIdEditRoute
}

const AdminTestimonialsRouteChildren: AdminTestimonialsRouteChildren = {
  AdminTestimonialsNewRoute: AdminTestimonialsNewRoute,
  AdminTestimonialsIndexRoute: AdminTestimonialsIndexRoute,
  AdminTestimonialsIdEditRoute: AdminTestimonialsIdEditRoute,
}

const AdminTestimonialsRouteWithChildren =
  AdminTestimonialsRoute._addFileChildren(AdminTestimonialsRouteChildren)

interface AdminRouteChildren {
  AdminBlogsRoute: typeof AdminBlogsRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogsRoute: AdminBlogsRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminTestimonialsRoute: AdminTestimonialsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ApplyRoute: ApplyRoute,
  BlogRoute: BlogRouteWithChildren,
  BookCampaignRoute: BookCampaignRoute,
  BrandsRoute: BrandsRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  CreatorsRoute: CreatorsRoute,
  PortfolioRoute: PortfolioRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestimonialsRoute: TestimonialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
